server:
  port: 8520
  servlet:
    context-path: /msc
spring:
  application:
    name: best-msc-binbin
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

# swagger 配置
knife4j:
  # 是否开启增强
  enable: true
  # 开启生产环境屏蔽
  production: false
  basic:
    enable: false
    username: test
    password: 123
  title: 罗网模块接口文档
  license: Powered By Jing
  licenseUrl:
  basePackage: com.jing.msc.binbin.controller

logging:
  level:
    com.jing.msc.binbin: debug

