server:
  port: 8520
  servlet:
    context-path: /msc
spring:
  application:
    name: best-msc-binbin
#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/static/
# springdoc-openapi 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match:
        - /**
      packages-to-scan:
        - com.jing.msc.binbin.controller
# knife4j 的增强配置
knife4j:
  # 是否开启增强
  enable: true
  # 开启生产环境屏蔽
  production: false
  setting:
    language: zh_cn
#  title: 罗网模块接口文档
  basic:
    enable: false
    username: test
    password: 123
#  contact:
#    name: jing
#    url: http://www.jing.com
#    email: flm894634186@qq.com
#  license:
#    name: Apache 2.0
#    url: http://www.apache.org/licenses/LICENSE-2.0
#  basePackage: com.jing.msc.binbin.controller
#  version: 1.0.0

logging:
  level:
    com.jing.msc.binbin: debug
