server:
  port: 8135
spring:
  application:
    name: best-msc-cobweb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cobweb_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    #    url: jdbc:mysql://localhost:3306/ivms_320_24?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Fullsee@123
    druid:
      # 配置初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 10000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 10000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 50000
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 20
      # 监控统计拦截的 filters
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  redis:
    host: 127.0.0.1
    port: 6379
    password: Fullsee@123

mybatis-plus:
  # 实体扫描，多个 package 用逗号或分号隔开
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.jing.msc.**.entity
  type-enums-package: com.jing.msc.**.enums
  global-config:
    db-config:
      # 主键类型
      id-type: assign_id
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略
      insert-strategy: not_empty
      update-strategy: not_empty
      # 表名是否使用驼峰转下划线命名,只对表名生效
      table-underline: true
      # 全局的entity的逻辑删除字段属性名,(逻辑删除下有效)
      logic-delete-field: logic_flag
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    # 开启Mybatis二级缓存，默认为 true
    cache-enabled: true
    # mybatis-plus配置SLF4J（控制台+文件）打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# springdoc-openapi 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match:
        - /**
      packages-to-scan:
        - com.jing.msc.cobweb.controller
# knife4j 的增强配置
knife4j:
  # 是否开启增强
  enable: true
  # 开启生产环境屏蔽
  production: false
  setting:
    language: zh_cn
  #  title: 罗网模块接口文档
  basic:
    enable: false
    username: test
    password: 123
#  contact:
#    name: jing
#    url: http://www.jing.com
#    email: flm894634186@qq.com
#  license:
#    name: Apache 2.0
#    url: http://www.apache.org/licenses/LICENSE-2.0
#  basePackage: com.jing.msc.binbin.controller
#  version: 1.0.0

logging:
  level:
    com.jing.msc.cobweb: debug

